### ISSUE TITLE
Gpt-4 models doesn't give any response 

### ISSUE THREAD

**Issue by kwekewk** [ading2210/openplayground-api#1]

**Comment by liej6799** [comment]
hi this is due to trim issue, can try follow this https://github.com/ading2210/openplayground-api/commit/c1f95eecfc6b97b66e7dc7b81c7cb9652d76f33b changes

**Comment by ading2210** [comment]
@liej6799 I've merged your changes, so this issue should be fixed now. Once I write the documentation for the Auth class, I'll release it to PyPi.
