### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by zjrwtx** [ading2210/openplayground-api#3]
![image](https://user-images.githubusercontent.com/86822589/226810655-2154b84f-a898-4f61-96a7-d2ffb1bcdb48.png)

**Comment by ading2210** [comment]
Looks like they've recently added SMS verification, which probably changed their authentication system. I'll probably publish a fix for this within a day. 

![image](https://user-images.githubusercontent.com/71154407/226812653-23fec162-9a7c-4f00-9711-4cfcd1f013b9.png)

**Comment by ading2210** [comment]
This has been fixed in version 0.0.3.

**Comment by zjrwtx** [comment]
> This has been fixed in version 0.0.3.

thanks！
