### ISSUE TITLE
whoops

### ISSUE THREAD

**Issue by xtekky** [ading2210/openplayground-api#4]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/98614666/228068832-e5d98ae0-3c3d-43d4-88dd-b46053e60191.png">

x-session gen omg, who wants it

**Comment by ading2210** [comment]
Sure, if you want to add it, just make a pull request. Just make sure everything has 2 spaces per tab to be consistent with the rest of the project.

**Comment by ading2210** [comment]
Also, would this allow for the generation of tokens that aren't tied to an actual account? If that's the case, then that'd be a pretty glaring security issue on their part.

**Comment by ading2210** [comment]
I ended up just implementing this myself in v0.1.0.

**Comment by xtekky** [comment]
ggs, I think they will change it soon but, I will reverse it if needed, did you get this solution yourself or did you inspire from my code ?

**Comment by ading2210** [comment]
I got the code myself, but I was prompted to do so by this issue.
